### ISSUE TITLE
任意输入命令都会提示“你没有执行该命令的权限”，所有命令都需要输入第二次才会生效

### ISSUE THREAD

**Issue by Hibari233** [way-zer/ScriptAgent4MindustryExt#13]
> permission @default add wayzer.ext.gather
你没有执行该命令的权限
permission @default add wayzer.ext.gather
[02-01-2021 16:43:41] [I] 添加权限wayzer.ext.gather到组@default
>

**Comment by way-zer** [comment]
这个是jline对windows兼容性的问题，我正在尝试优化

**Comment by Hibari233** [comment]
好的

**Comment by Hibari233** [comment]
还有您知道服务器经常就假死不动 游戏内输入/help没反应 需要去服务端控制台敲几下回车才会有反应是怎么回事嘛

**Comment by way-zer** [comment]
> 还有您知道服务器经常就假死不动 游戏内输入/help没反应 需要去服务端控制台敲几下回车才会有反应是怎么回事嘛

控制台处于选定状态会卡死服务器

**Comment by way-zer** [comment]
修复了core/console脚本。现在在windows下应该正常了，还能使用TAB补全等功能

**Comment by way-zer** [comment]
最新的脚本包可以在actions下载https://github.com/way-zer/ScriptAgent4MindustryExt/actions/runs/527516878

**Comment by Hibari233** [comment]
好的
