### ISSUE TITLE
第一次运行: IndexOutOfBoundsException

### ISSUE THREAD

**Issue by purofle** [way-zer/ScriptAgent4MindustryExt#2]
脚本加载结束时出现：
![Screenshot_20200827_214138](https://user-images.githubusercontent.com/37149302/91449877-3935c480-e8ae-11ea-95cf-efd3ad3b351d.jpg)
运行host时出现：
![Screenshot_20200827_214145](https://user-images.githubusercontent.com/37149302/91449925-49e63a80-e8ae-11ea-88a9-f3ac6b59514b.jpg)
使用openjdk11,请问如何解决？

**Comment by way-zer** [comment]
Oh, 这个报错说明你没有加地图, 通过```sa config wayzer.maps.configEnableInternMaps set true ```开启游戏自带地图，或者添加地图解决

**Comment by purofle** [comment]
好的谢谢
