### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Kieaer** [way-zer/ScriptAgent4MindustryExt#22]
### Plugin
- [x] Command
- [x] Texts
### Github
- [ ] English wiki (Translate service isn't perfectly)
- [ ] readme (write last line)
## Experiences
- [x] using player name instead uuid if possible
First, search ``Groups.player`` -> if not exists -> find name in ``netServer.admins`` -> is not exists -> search uuid
- [x] Find players using ID number (useful if player name is complex)
Use ``player.id()``
## Bugs
- [x] Fix command not visiable from Windows Terminal system (legacy is working but new terminal isn't work)

I going to lunch 😄

**Comment by way-zer** [comment]
> Experiences[1] use name

I prefer `uuid` for security. 

> Experiences[2] use id

I used prefix(3 digtial) of hashed `uuid`, which ensure the same when rejoining or in other servers.

**Comment by way-zer** [comment]
After v3.0.0 build 39. All commands' `desc` is translatable. and support `Player.locale`
