### ISSUE TITLE
Can't download ScriptAgent library

### ISSUE THREAD

**Issue by Kieaer** [way-zer/ScriptAgent4MindustryExt#25]
Time to ask this issue.
The library in issue is this ``https://maven.tinylake.tk/cf/wayzer/ScriptAgent/1.10.1.2/ScriptAgent-1.10.1.2.jar``

Downloads are terribly slow or can't connect.
I'm suggested to use jitpack after uploading the library or source to Github.

I thought it was just my internet problem, but now it doesn't seem to be.

**Comment by way-zer** [comment]
## About the repo
The `tinylake.tk` is mirror using CloudFalre, backend is aliyun maven located in China mainland. The network quality between mirror and the backend varies in different regions. 
You can change the if candition in `build.gradle.kts` to try using the backend. or see https://github.com/TinyLake/maven for detail.

I don't know other free repository. Github package may be a good place, but it needs login for user. 

## About the library file
The core library is not ready for open source, so I can't publish it to public repository.(mavenCentral or jitpack)  
I want to keep the core a black box, easy to use. Less compatibility constraints for better function.
I promise it's safe to use, no malicious code, or you can verify this by decompiling(no obfuscation).
