### ISSUE TITLE
加载wayzer/user/ext/rank时发生错误

### ISSUE THREAD

**Issue by lemon3357** [way-zer/ScriptAgent4MindustryExt#29]
pgsql版本:14.10.1
driver版本:42.7.1
[DefaultDispatcher-worker-4] WARN Exposed - Transaction attempt #1 failed: org.postgresql.util.PSQLException: 错误: 当前事务被终止, 事务块结束之前的查询被忽略. Statement(s): DELETE FROM busy
org.jetbrains.exposed.exceptions.ExposedSQLException: org.postgresql.util.PSQLException: 错误: 函数 current_week() 不存在
Hint: 没有匹配指定名称和参数类型的函数. 您也许需要增加明确的类型转换.
Position: 255
SQL: [CREATE TABLE IF NOT EXISTS rankdata (id INT NOT NULL, "name" VARCHAR(36) DEFAULT 'UNKNOWN' NOT NULL, "onlineTime" INT DEFAULT 0 NOT NULL, "exp" INT DEFAULT 0 NOT NULL, played INT DEFAULT 0 NOT NULL, win INT DEFAULT 0 NOT NULL, "weekUpdate" DATE DEFAULT (current_week()) NOT NULL, "onlineTimeWeek" INT DEFAULT 0 NOT NULL, "expWeek" INT DEFAULT 0 NOT NULL, "playedWeek" INT DEFAULT 0 NOT NULL, "winWeek" INT DEFAULT 0 NOT NULL, CONSTRAINT fk_rankdata_id__id FOREIGN KEY (id) REFERENCES playerprofile(id) ON DELETE CASCADE ON UPDATE RESTRICT)][]

**Comment by lemon3357** [comment]
刚才没打表 我还以为好了(

**Comment by way-zer** [comment]
current_week的sql在代码中。试试手动执行下？

**Comment by lemon3357** [comment]
好了 谢谢wz

**Comment by Xiao-yux** [comment]
![image](https://github.com/way-zer/ScriptAgent4MindustryExt/assets/79674967/c152193a-1a91-4e39-9fd7-07168d2ad267)
这个怎么解决

**Comment by way-zer** [comment]
[rank.dao.kt.txt](https://github.com/way-zer/ScriptAgent4MindustryExt/files/14588483/rank.dao.kt.txt)
试试这个，替换`wayzer/user/ext/rank.dao.kt`

**Comment by Xiao-yux** [comment]
![image](https://github.com/way-zer/ScriptAgent4MindustryExt/assets/79674967/116ecec9-151b-4e7a-a240-a38d47b9433b)
需不需要配置这个

**Comment by way-zer** [comment]
肯定需要呀

**Comment by Xiao-yux** [comment]
> 肯定需要呀
![image](https://github.com/way-zer/ScriptAgent4MindustryExt/assets/79674967/b1f76132-d515-4b1c-a9ec-9bfca25265b2)
help

**Comment by way-zer** [comment]
换数据库是高级用法，请按dbConnector里面的说明来。
