### ISSUE TITLE
地图未显示

### ISSUE THREAD

**Issue by 44wrw44** [way-zer/ScriptAgent4MindustryExt#31]
在 v3.1.2 插件中，地图不会显示在 /maps 命令中，但可以通过 /vote 地图进行更改。

**Comment by way-zer** [comment]
已经修了 https://github.com/way-zer/ScriptAgent4MindustryExt/commit/6dd3dc6f4579b43fe5fb0a4ebdc2d92aac75cc34.
你可以下载源码中相关文件

**Comment by Xiao-yux** [comment]
> 已经修了 [6dd3dc6](https://github.com/way-zer/ScriptAgent4MindustryExt/commit/6dd3dc6f4579b43fe5fb0a4ebdc2d92aac75cc34). 你可以下载源码中相关文件

地图文件放在哪里，我放在./config/maps 中，使用maps指令，不显示地图。把mod关了，用原版就显示

**Comment by way-zer** [comment]
> > 已经修了 [6dd3dc6](https://github.com/way-zer/ScriptAgent4MindustryExt/commit/6dd3dc6f4579b43fe5fb0a4ebdc2d92aac75cc34). 你可以下载源码中相关文件
> 
> 地图文件放在哪里，我放在./config/maps 中，使用maps指令，不显示地图。把mod关了，用原版就显示

原版目录。不过因为`wayzer/maps`相关代码有bug，请手动更新下。Github下载对应kts和kt放到scripts目录即可

**Comment by Xiao-yux** [comment]
Reason: typeMismatch
使用arc端进不了游戏，怎么配置啊

**Comment by Xiao-yux** [comment]
> > > 已经修了 [6dd3dc6](https://github.com/way-zer/ScriptAgent4MindustryExt/commit/6dd3dc6f4579b43fe5fb0a4ebdc2d92aac75cc34).你可以下载源码中相关文件
> > 
> > 
> > 地图文件放在哪里，我放在./config/maps 中，使用maps指令，不显示地图。把mod关了，用原版就显示
> 
> 原版目录。不过，因为相关代码有bug，请手动更新下。Github下载对应kts和kt放到scripts目录即可`wayzer/maps`

![image](https://github.com/way-zer/ScriptAgent4MindustryExt/assets/79674967/095daf94-d540-4d6d-8575-8117e44a24db)
这个是什么原因

**Comment by way-zer** [comment]
游戏版本不匹配

PS: 请不要在别人的Issue发不相关的问题
