### ISSUE TITLE
Is the resource still available? ScriptAgent library

### ISSUE THREAD

**Issue by NR-The-Void** [way-zer/ScriptAgent4MindustryExt#33]
because when I visit the link it tells me that the resource is no longer available

https://packages.aliyun.com/maven/repository/2102713-release-0NVzQH

Etat HTTP 404 - Resource does not exist
type Status report

message Resource does not exist

description The requested resource is not available.

Apache Tomcat/7.0.64.944

**Comment by way-zer** [comment]
This is maven repository, not supporting list, see https://github.com/TinyLake/maven

**Comment by way-zer** [comment]
If you are outside China, you will use `maven.tinylake.tk`, that is unavailable. Replace with `maven.tinylake.tech`.

**Comment by NR-The-Void** [comment]
oh thank you very much, now it's working
