### ISSUE TITLE
How to put maps?

### ISSUE THREAD

**Issue by DemuraAIdev** [way-zer/ScriptAgent4MindustryExt#34]
when i place maps in maps folder its not loaded

**Comment by way-zer** [comment]
#31 
Fixed in https://github.com/way-zer/ScriptAgent4MindustryExt/commit/6dd3dc6f4579b43fe5fb0a4ebdc2d92aac75cc34

You can download the source about `wayzer/maps` and put them into scripts.
I will keep the issue open until next release.

**Comment by DemuraAIdev** [comment]
okay
