### ISSUE TITLE
How can i disable ths

### ISSUE THREAD

**Issue by DemuraAIdev** [way-zer/ScriptAgent4MindustryExt#35]
![image](https://github.com/way-zer/ScriptAgent4MindustryExt/assets/71892583/6af1ab3b-932b-4457-986b-4330835a8300)
version 7.5 (latest)
how to get rid the gray box in the middle of core?

**Comment by way-zer** [comment]
`wayzer/map/mapInfo.kts`
And this only show 2 minutes for one player.
