### ISSUE TITLE
Random Diconnect when play

### ISSUE THREAD

**Issue by DemuraAIdev** [way-zer/ScriptAgent4MindustryExt#36]
![image](https://github.com/way-zer/ScriptAgent4MindustryExt/assets/71892583/dd499e07-e2f3-4e34-9631-e0ab0a51c2e6)
![image](https://github.com/way-zer/ScriptAgent4MindustryExt/assets/71892583/a9684094-9537-4370-a12b-9b7fb3b6f6bf)

Version Lastest (Build) 7.5
i Cant join server again when disconnect(timeout) but in server there is no indicate error or something but i diconnect because timeout, but after a minute i can join again and again...

**Comment by way-zer** [comment]
This may be network problem, not sure it have something with the plugin.

Try `status` in console to check if the server is not response or network problem.
