### ISSUE TITLE
Maps detect as survival

### ISSUE THREAD

**Issue by DemuraAIdev** [way-zer/ScriptAgent4MindustryExt#37]
![image](https://github.com/way-zer/ScriptAgent4MindustryExt/assets/71892583/82379e07-a3f4-4af2-82f5-1dad138d6054)
Maps "The Rift" should be PVP why its survival?

**Comment by way-zer** [comment]
You should rename your map file name, starting with `P`. As no way to get mode from msav.

Inherit from https://github.com/way-zer/MyMindustryPlugin
> 重写默认换图机制(可以根据文件名首字母确定模式 S生存P对抗A攻击C沙盒创造E编辑器模式)

> **S**urvive, **P**vp, **A**ttack, **C**reative/Sandbox, **E**ditor
