### ISSUE TITLE
/ob

### ISSUE THREAD

**Issue by 44wrw44** [way-zer/ScriptAgent4MindustryExt#38]
in /ob all teams on version 146 are not displayed, only the first one installed as a player (in PVP mode)
![image](https://github.com/way-zer/ScriptAgent4MindustryExt/assets/73754757/bdd93614-1071-43df-ae83-9cb014a24a52)
_(Don't pay attention to the translation, I Russified it)_

**Comment by way-zer** [comment]
Don't know how is your PVP mode. The team is calculated through this code
https://github.com/way-zer/ScriptAgent4MindustryExt/blob/ac51a4a7b416d4d53a59ad8b97f07852e837d9ec/scripts/wayzer/map/betterTeam.kts#L25-L33

_(Do you translate using language? World you like to share it?)_

**Comment by 44wrw44** [comment]
And under what conditions does he choose teams?

**Comment by 44wrw44** [comment]
I just noticed that it only displays the player’s core and even /team doesn’t see the other cores

**Comment by way-zer** [comment]
`/team` is also for pvp, so only players'teams are allowed.

**Comment by way-zer** [comment]
> And under what conditions does he choose teams?

What mean? The variable is calculated everytime when accessing.

**Comment by 44wrw44** [comment]
He sees only the team of players that is set in the map editor; the second base, which is set as the opponent, is not defined as a team selection option. Therefore pvp is not playable.

**Comment by way-zer** [comment]
> He sees only the team of players that is set in the map editor; the second base, which is set as the opponent, is not defined as a team selection option. Therefore pvp is not playable.

Do you play a map with PVP mode? or just survive mode?

**Comment by 44wrw44** [comment]
In pvp mode, at least in /maps it is displayed as pvp

**Comment by way-zer** [comment]
> In pvp mode, at least in /maps it is displayed as pvp

Other teams have cores?
Could you provide the map file?

**Comment by 44wrw44** [comment]
[PInterstellar.msav.zip](https://github.com/way-zer/ScriptAgent4MindustryExt/files/15286090/PInterstellar.msav.zip)

**Comment by way-zer** [comment]
> [PInterstellar.msav.zip](https://github.com/way-zer/ScriptAgent4MindustryExt/files/15286090/PInterstellar.msav.zip)

This map trigger backCompatibility, which banned waveTeam.
https://github.com/way-zer/ScriptAgent4MindustryExt/blob/ac51a4a7b416d4d53a59ad8b97f07852e837d9ec/scripts/wayzer/map/backCompatibility.kts#L22-L23

The backCompatibility is due to some map use waveTeam(red) as neutral team. Which is defaultly banned in old plugin.
If you don't need, you can just remove this.
