### ISSUE TITLE
host failed

### ISSUE THREAD

**Issue by Baldur404** [way-zer/ScriptAgent4MindustryExt#40]
good server plugin ,it make my grandma Binzhou rotation

**Comment by way-zer** [comment]
Check your server network to resource site, or disable using resource site.

token can't be `false`, only emply.

You should know how to use `sa config`. This function is enabled manually. Now that you know how to enable it, you should also know how to use `reset` to reset the settings.

**Comment by way-zer** [comment]
Notes that, issue description was edited by the author.
