### ISSUE TITLE
gpl

### ISSUE THREAD

**Issue by deltanedas** [way-zer/ScriptAgent4MindustryExt#9]
> Plugin：Reprinting and other uses (including decompiling not for use) are prohibited without permission

Mindustry is GPLv3 and since you compile against it, this plugin is also GPLv3.

**Comment by way-zer** [comment]
There are some problems in plugin. 
1. The main library used in plugin is not compatibilible with GPLv3.
2. All parts refered Mindustry are open. These are Ok
These is why I just use words instead select one license file.

~~If the problem 1 can't be accepted, I may close this project to work on https://github.com/way-zer/ScriptAgentstandalone.
In which, I will load Mindustry as a module. So All code related to Mindustry can be GPLv3 compatibilible.~~

**Comment by way-zer** [comment]
As I know, Bukkit is GPLv3, but not all plugin is GPLv3.
If you accept the lisence, you can use this project.
The plugin can't be GPLv3, but I want to let more use it.

**Comment by way-zer** [comment]
Close for not active
